# Generated by Django 5.2.4 on 2025-07-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberShipForm',
            fields=[
                ('form_slug', models.CharField(primary_key=True, serialize=False)),
                ('title', models.CharField()),
                ('description', models.CharField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
