# Generated by Django 5.2.4 on 2025-07-28 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberShipForm',
            fields=[
                ('form_slug', models.CharField(primary_key=True, serialize=False)),
                ('title', models.CharField()),
                ('form_type', models.CharField()),
                ('description', models.CharField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MemberShipFormOrder',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('payer_email', models.CharField()),
                ('payer_first_name', models.CharField()),
                ('payer_last_name', models.CharField()),
                ('updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloAssoImporter.membershipform')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField()),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('birhdate', models.DateField()),
                ('email', models.CharField()),
                ('licence_number', models.CharField(blank=True, default='')),
                ('sex', models.CharField()),
                ('caci_expiration', models.DateField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloAssoImporter.membershipformorder')),
            ],
        ),
    ]
