# Generated by Django 5.2.4 on 2026-03-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloAssoImporter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventForm',
            fields=[
                ('form_slug', models.CharField(primary_key=True, serialize=False)),
                ('title', models.CharField()),
                ('form_type', models.CharField()),
                ('description', models.CharField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('last_registration_updated', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
