# Generated by Django 5.2.4 on 2026-04-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helloAssoImporter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipformorder",
            name="emergency_contact_name",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="membershipformorder",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, default=""),
        ),
    ]
