# Generated by Django 5.2.4 on 2026-04-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "helloAssoImporter",
            "0002_membershipformorder_emergency_contact_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="medical_certificate_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
