# Generated by Django 5.2.4 on 2026-03-09 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloAssoImporter', '0002_eventform'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFormOrder',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloAssoImporter.eventform')),
            ],
        ),
    ]
