# Generated by Django 5.2.4 on 2026-03-09 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloAssoImporter', '0003_eventformorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventformorder',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='eventformorder',
            name='payer_email',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='eventformorder',
            name='payer_first_name',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='eventformorder',
            name='payer_last_name',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='eventformorder',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloAssoImporter.eventformorder')),
            ],
        ),
    ]
