# Generated by Django 5.2.4 on 2026-04-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloAssoImporter', '0003_member_medical_certificate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
