# Generated by Django 5.2.4 on 2026-04-20 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloAssoImporter', '0004_member_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(help_text='Date de version du cursus')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('archived', 'Archivé')], default='active', max_length=20)),
            ],
            options={
                'verbose_name': 'Cursus',
                'verbose_name_plural': 'Cursus',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CursusCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('cursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='helloAssoImporter.cursus')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='helloAssoImporter.cursuscategory')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SkillEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('not_acquired', 'Non acquis'), ('in_progress', "En cours d'acquisition"), ('acquired', 'Acquis')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_evaluations', to='helloAssoImporter.member')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='helloAssoImporter.skill')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MemberSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_acquired', 'Non acquis'), ('in_progress', "En cours d'acquisition"), ('acquired', 'Acquis')], default='not_acquired', max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_skills', to='helloAssoImporter.member')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_skills', to='helloAssoImporter.skill')),
            ],
            options={
                'verbose_name': 'Compétence membre',
                'verbose_name_plural': 'Compétences membres',
                'constraints': [models.UniqueConstraint(fields=('member', 'skill'), name='unique_member_skill')],
            },
        ),
    ]
