# Generated by Django 5.2.4 on 2026-04-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloAssoImporter', '0005_cursus_cursuscategory_skill_skillevaluation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='formations',
            field=models.ManyToManyField(blank=True, related_name='members', to='helloAssoImporter.cursus'),
        ),
    ]
