# Generated by Django 5.2.4 on 2026-03-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='invite_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='invite_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
