# Generated by Django 5.2.4 on 2026-03-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0002_customuser_invite_token_customuser_invite_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='invite_url',
        ),
        migrations.AddField(
            model_name='customuser',
            name='invite_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
